kind: Service
apiVersion: v1
metadata:
  name: fess-es
  labels:
    app: "fess-es"
  annotations:
    {}
spec:
  type: ClusterIP
  selector:
    app: "fess-es"
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.es.httpPort }}
  - name: transport
    protocol: TCP
    port: {{ .Values.es.transportPort }}
---
kind: Service
apiVersion: v1
metadata:
  name: fess-es-headless
  labels:
    app: "fess-es"
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  clusterIP: None # This is needed for statefulset hostnames like elasticsearch-0 to resolve
  # Create endpoints also if the related pod isn't ready
  publishNotReadyAddresses: true
  selector:
    app: "fess-es"
  ports:
  - name: http
    port:  {{ .Values.es.httpPort }}
  - name: transport
    port:  {{ .Values.es.transportPort }}
